[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[programs.devnet]
token_sale = "Bv8sK4AN9bTrcLfH8zvCs8yiScbQZtT8nnss5uEticDe"

[workspace]
members = [
    "programs/*",
]

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[toolchain]
anchor_version = "0.31.1"

[registry]
url = "https://anchor.projectserum.com"

[features]
seeds = false
skip-lint = false